esphome:
  name: watermeter
  platform: ESP8266
  board: d1_mini
  includes:
    - hmc5883l.h

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 192.168.2.126
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "WaterMeter Fallback Hotspot"
    password: "useyourownpassword"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:


web_server:
  port: 80
  


sensor:
- platform: custom
  lambda: |-
    auto watersensor = new WaterMeterSensor();
    App.register_component(watersensor);
    return {watersensor};

  sensors:
    name: "Water Meter Sensor"
    unit_of_measurement: L/Hr
    
    